FROM ubuntu:18.04

# Install Nginx. 
RUN apt-get update 
RUN apt-get install -y nginx

# Copy index.html
COPY index.html /var/www/html/index.nginx-debian.html

# Define working directory. 
WORKDIR /etc/nginx 

# Define default command.
CMD ["nginx", "-g", "daemon off;"] 

# Expose ports. 
EXPOSE 80